# Generated by Django 3.0.5 on 2020-05-10 12:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeMembre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_gpe', models.CharField(max_length=30, verbose_name='nom du groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('niv_etu', models.CharField(max_length=30, verbose_name="niveau d'étude")),
                ('filiere', models.CharField(max_length=30, verbose_name='filière')),
                ('genre', models.CharField(max_length=1, verbose_name='genre')),
            ],
            options={
                'verbose_name': ('membre',),
                'verbose_name_plural': 'membres',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('secrétaire',),
                'verbose_name_plural': 'secrétaires',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MembreAdhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'adhésion")),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.GroupeMembre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Membre')),
            ],
        ),
        migrations.AddField(
            model_name='groupemembre',
            name='membres',
            field=models.ManyToManyField(through='users.MembreAdhesion', to='users.Membre'),
        ),
    ]
